---
title: "Session 3"
output: word_document
date: "2025-01-16"
---

```{r setup}
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE)

for(packageName in c("devtools",            # 
                     "here",
                     "magrittr",
                     "phaseR",
                     "tidyverse")) {
  if(!is.element(packageName,               # If package is NOT installed...
                 installed.packages()[,1])) {
    install.packages(packageName)           #  ...then install it.
  }
  library(packageName,                      # Add package to environment
          character.only=TRUE,
          quietly=TRUE,
          verbose=FALSE)
}

i_am("Scripts/Session 3.Rmd")   # To help find all the files.

source(here("Scripts/Folders.R"))           # Make sure folders exist.

install_github("barneyricca/ndstools")

options(show.signif.stars = FALSE)          # Don't stargaze
options(digits = 3)                         # Round to 3 digits by default
```

# Slide 8

```{r}
c(0, 0, 0, 0, 2, 4, 6, 4, 4, 2, 2, 0) -> A
c(0, 0, 2, 4, 6, 4, 4, 2, 2, 0, 0, 0) -> B
sum(abs(B-A))
c(1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 1) -> C
sum(abs(C-A))

png(filename = here("Images/Session 3 Slide 8a.png"),
    width = 5,
    height = 5,
    units = "in",
    res = 600)
{
  plot(A, type = 'l',
       ylab = "A and B")
  lines(B, col = "blue")
}
dev.off()

png(filename = here("Images/Session 3 Slide 8b.png"),
    width = 5,
    height = 5,
    units = "in",
    res = 600)
{
  plot(A, type = 'l',
       ylab = "A and C")
  lines(C, col = "blue")
}
dev.off()

```

# Slide 9

```{r}

# Re-use Session 3 Slide 8a

png(filename = here("Images/Session 3 Slide 9b.png"),
    width = 5,
    height = 5,
    units = "in",
    res = 600)
{
  plot(A, type = 'l',
    xlab = "A and (B shifted by 2)",
    ylab = "A and B")
  points(A, col = "blue")
}
dev.off()

```


# Slide 10

This dynamic warping of time allows us to see that these two data streams are essentially the same.

```{r}
c(0, 0, 0, 0, 2, 4, 6, 4, 4, 2, 2, 0) -> A
c(0, 2, 2, 4, 4, 6, 6, 4, 2, 2, 0, 0) -> D
D + 1 ->                                    # To make it easier to see the
  D                                         #  connections
1:length(A) -> t

png(filename = here("Images/Session 3 Slide 10.png"),
    width = 10,
    height = 5,
    units = "in",
    res = 600)
{
  plot(A, 
       type = 'l',
       lwd = 2,
       ylab = "Data",
       ylim = c(0,8))
  points(A, 
         pch = 16, 
         cex = 0.7)
  lines(D, 
        col = "blue",
        lwd = 2)
  points(D,
         pch = 16,
         cex = 0.7,
         col = "blue")
  segments(x0 = t,
           y0 = A,
           x1 = c(1,1,1,1,3,5,7,8,8,10,10,11),
           y1 = D[c(1,1,1,1,3,5,7,8,8,10,10,11)],
           lwd = 0.6)
}
dev.off()

sum(abs(A-D)) - 12
sum(abs(A - D[c(1,1,1,1,3,5,7,8,8,10,10,11)])) - 12

```


