---
title: "Entropy"
output: word_document
date: "2025-01-16"
---


```{r setup}
#| include: FALSE
knitr::opts_chunk$set(echo = TRUE)

for(packageName in c("devtools",            # R packages needed here
                     "here",
                     "magrittr",
                     "tidyverse")) {
  if(!is.element(packageName,               # If package is NOT installed...
                 installed.packages()[,1])) {
    install.packages(packageName)           #  ...then install it.
  }
  library(packageName,                      # Add package to environment
          character.only=TRUE,
          quietly=TRUE,
          verbose=FALSE)
}

i_am("Scripts/Session 5 - Entropy.Rmd")     # To help find all the files.

install_github("barneyricca/ntls_tools")    # Specialized NLTS tools
library(ntls_tools)

source(here("Scripts/Folders.R"))           # Make sure folders exist.

options(show.signif.stars = FALSE)          # Don't stargaze
options(digits = 3)                         # Round to 3 digits by default
```

Entropy: Use table() for probabilities

```{r data}

```


